# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.0
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: codeepoch@gmail.com
author_name: Zaibatsu-Group
cloud_provider: none
contract_name: zaibatsu
deployment_language: python
ide_jetbrains: false
ide_vscode: false
preset_name: starter
project_name: zaibatsu
python_linter: none
use_dispenser: false
use_github_actions: true
use_python_black: true
use_python_mypy: false
use_python_pip_audit: true
use_python_pytest: true

